### ISSUE TITLE
Handling duplicate rows in samplesheet with warnings

### ISSUE THREAD

**Issue by mvheetve** [nf-cmgg/structural#67]
### Warnings for duplicate sample sheet rows

When the samplesheet contains duplicate rows, it now says:

```
Samplesheet errors:
	The samplesheet contains duplicate rows for entry 5 and entry 17 ([sample:sample1, cram:s3://cmgg-results/WGS/cram/.../sample1/sample1.cram, crai:s3://cmgg-results/WGS/cram/.../sample1/sample1cram.crai])
```

Maybe it would be better if you issue a warning and proceed with the pipeline, ignoring any duplicated instances. 

Just a thought
Mattias

**Comment by nvnieuwk** [comment]
Hi, this is fully intended behaviour. You don't want to process the exact same files more than once. Files coming from separate sources will not trigger this error, because their file path should be different. You can just remove one of the duplicate rows and it will run fine.
