### ISSUE TITLE
--callers all param

### ISSUE THREAD

**Issue by mvheetve** [nf-cmgg/structural#84]
### Description of feature

It would be lovely if `--callers` had the `all` option, instead of having to make a comma separated list of all callers.

**Comment by matthdsm** [comment]
It would be even better if all callers were ENabled by default and you can disable then through the cli IMO

**Comment by nvnieuwk** [comment]
The most sensible ones are now the default (which is all but one at the moment).

**Comment by nvnieuwk** [comment]
Added in #85
